### ISSUE TITLE
Add piping functionality to work with ggplot/dplyr

### ISSUE THREAD

**Issue by jzadra** [tdhock/directlabels#10] opened 2017-02-24 17:06 UTC
The `tidyverse` functions (`dplyr`) work with piping where 
`x %>% f(y)`
becomes 
`f(x, y)`

This makes it easy to chain a series of commands to filter, mutate, etc the data before plotting. It would be great if directlabels also accepted piped inputs so that it could be the final step without having to surround the entire statement or save the plot as an object first.  Currently this is the way to apply direct labels to a ggplot:
`require(tidyverse)`
`require(directlabels)`

`p <- ggplot(diamonds, aes(x = depth, color = cut)) + geom_density()`
`direct.label(p, "top.bumptwice")`

Here is how it would look with piping:

`diamonds %>% `
  `    ggplot(aes(x = depth, color = cut)) + geom_density() %>% `
  `    direct.label("top.bumptwice")`

**Comment by tdhock** [comment] 2017-03-24 20:50
it works for me if you put the parenthesis in the right place:
```
(diamonds %>%
ggplot(aes(x = depth, color = cut)) + geom_density()) %>%
direct.label("top.bumptwice")
```
the problem is that `%>%` is evaluated before `+` -- you may want to tell the magrittr people about this issue, but I am closing it here.

**Closed by tdhock** 2017-03-24 20:50 UTC
