### ISSUE TITLE
Labels for LARS plot

### ISSUE THREAD

**Issue by arr951** [tdhock/directlabels#33] opened 2021-02-08 23:34 UTC
I am analyzing my data using Least Angle Regression (LAR) methods using the "lars" package. I would like to create a quality plot using ggplot2 and then put labels for each line using "directlablels" package. 
I can create the LARS plot using ggplot2, but when I use the functions of directlablels package (such as direct.label (p,"maxvar.points"), I get an error message (see below):

#error message---------------------------------------------------
"Error in parse(text = elt) : <text>:2:0: unexpected end of input 1: ~ ^"
In addition: Warning message:
Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
Please use `as_label()` or `as_name()` instead.
#---------------------------------------------------------------------------------
#Here are my codes

# 09/02/2021
# Lars plot using ggplot2

library(ggplot2); library(lars);library(devtools); library(reshape2); library(ElemStatLearn); 
library(directlabels); library(quadprog)

##################################################
# Lars plot using AMR data
# ========================================
# A) Creating LARS plot using lars package 
#========================================
rm(list=ls())

setwd("D:/Data_2")
dat <- read.csv("AMR_DDDRate_V2.csv", sep=",", header=TRUE, na.string=NA)
names(dat)

# delete rows with zero data for HA_MRSA variable
dat1 <- dat[-c(3, 7, 9,10,17,19,22),]
dat1$HA_MRSA

# In this model, we tested the model after removing the zero data for HA_MRSA variable
m0 <-lars(x=as.matrix(dat1[,-c(1:5)]),y=dat1[,3],type="lar",normalize=TRUE)  

x11()
plot(m0);# suggests 3 steps
title("HA_MRSA >0", adj = 0, line = 2.5, col="blue")
print(m0)

#=========================================
# B) creating LARS plot using ggplot2
#========================================
names(dat)

ycol <- which(names(dat)=="HA_MRSA")
x <- as.matrix(dat[-ycol])
y <- dat[[ycol]]

library(lars)
fit <-lars(x=as.matrix(dat1[,-c(1:5)]),y=dat1[,3],type="lar",normalize=TRUE)  # type="lasso"
beta <- scale(coef(fit),FALSE,1/fit$normx)
arclength <- rowSums(abs(beta))/max(rowSums(abs(beta)))    # LARS

library(reshape2)
path <- data.frame(melt(beta),arclength)
names(path)[1:3] <- c("step","variable","standardized.coef")

library(ggplot2)
p1 <- ggplot(path,aes(arclength,standardized.coef,colour=variable))+
  geom_line(aes(group=variable))+
  ggtitle("LASSO path for HA_MRSA data calculated using the LARS")+
  theme(legend.position = "none") +
  xlab("Sum of beta/max of sum of beta")+
  ylab("standardised coefficinets") +
  xlim(0,1)

x11(); p1

# direct.label(p,"angled.boxes")
direct.label(p1,"angled.boxes")   # this creates the error message (see below)

## Error Message #----------------------------------------------------------
#Error in parse(text = elt) : <text>:2:0: unexpected end of input 1: ~ ^
  
#In addition: Warning message:
#Using `as.character()` on a quosure is deprecated as of rlang 0.3.0.
#Please use `as_label()` or `as_name()` instead.
#----------------------------------------------------------------------------------
[AMR_DDDRate_V2.xlsx](https://github.com/tdhock/directlabels/files/5947457/AMR_DDDRate_V2.xlsx)

[Lars plot using ggplot2_Toby_2021_R Codes.pdf](https://github.com/tdhock/directlabels/files/5947521/Lars.plot.using.ggplot2_Toby_2021_R.Codes.pdf)
# Note: I will be ok with any other label options in your package.

#END
#############################################################################################

**Comment by tdhock** [comment] 2021-02-09 06:40
hi I am unable to reproduce the error you are getting. can you please try to simplify the code? https://stackoverflow.com/help/minimal-reproducible-example
I used the following code and it works fine
```r
if(!file.exists("prostate.data")){
  download.file(
    "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/prostate.data",
    "prostate.data")
}
prostate <- read.table("prostate.data")
pros <- subset(prostate,select=-train,train==TRUE)
ycol <- which(names(pros)=="lpsa")
x <- as.matrix(pros[-ycol])
y <- pros[[ycol]]
fit <- lars::lars(x,y,type="lasso")
beta <- scale(coef(fit),FALSE,1/fit$normx)
arclength <- rowSums(abs(beta))
path <- data.frame(reshape2::melt(beta),arclength)
names(path)[1:3] <- c("step","variable","standardized.coef")
library(ggplot2)
p <- ggplot(path,aes(arclength,standardized.coef,colour=variable))+
  geom_line(aes(group=variable))+
  ggtitle("LASSO path for prostate cancer data calculated using the LARS")+
  xlim(0,20)
library(directlabels)
direct.label(p, dl.combine("right.polygons", "lasso.labels"))
devtools::session_info()
```
this is with all CRAN packages updated:
```
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Ubuntu 18.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US:en                    
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Phoenix             
 date     2021-02-08                  

─ Packages ───────────────────────────────────────────────────────────────────
 package      * version   date       lib source        
 assertthat     0.2.1     2019-03-21 [1] CRAN (R 4.0.0)
 cachem         1.0.3     2021-02-04 [1] CRAN (R 4.0.3)
 callr          3.5.1     2020-10-13 [1] CRAN (R 4.0.3)
 cli            2.3.0     2021-01-31 [1] CRAN (R 4.0.3)
 colorspace     2.0-0     2020-11-11 [1] CRAN (R 4.0.3)
 crayon         1.4.1     2021-02-08 [1] CRAN (R 4.0.3)
 DBI            1.1.1     2021-01-15 [1] CRAN (R 4.0.3)
 desc           1.2.0     2018-05-01 [1] CRAN (R 4.0.0)
 devtools       2.3.2     2020-09-18 [1] CRAN (R 4.0.2)
 digest         0.6.27    2020-10-24 [1] CRAN (R 4.0.3)
 directlabels * 2021.1.13 2021-01-16 [1] CRAN (R 4.0.3)
 dplyr          1.0.4     2021-02-02 [1] CRAN (R 4.0.3)
 ellipsis       0.3.1     2020-05-15 [1] CRAN (R 4.0.0)
 farver         2.0.3     2020-01-16 [1] CRAN (R 4.0.0)
 fastmap        1.1.0     2021-01-25 [1] CRAN (R 4.0.3)
 fs             1.5.0     2020-07-31 [1] CRAN (R 4.0.3)
 generics       0.1.0     2020-10-31 [1] CRAN (R 4.0.3)
 ggplot2      * 3.3.3     2020-12-30 [1] CRAN (R 4.0.3)
 glue           1.4.2     2020-08-27 [1] CRAN (R 4.0.2)
 gtable         0.3.0     2019-03-25 [1] CRAN (R 4.0.0)
 labeling       0.4.2     2020-10-20 [1] CRAN (R 4.0.3)
 lars           1.2       2013-04-24 [1] CRAN (R 4.0.0)
 lifecycle      0.2.0     2020-03-06 [1] CRAN (R 4.0.0)
 magrittr       2.0.1     2020-11-17 [1] CRAN (R 4.0.3)
 memoise        2.0.0     2021-01-26 [1] CRAN (R 4.0.3)
 munsell        0.5.0     2018-06-12 [1] CRAN (R 4.0.0)
 pillar         1.4.7     2020-11-20 [1] CRAN (R 4.0.3)
 pkgbuild       1.2.0     2020-12-15 [1] CRAN (R 4.0.3)
 pkgconfig      2.0.3     2019-09-22 [1] CRAN (R 4.0.0)
 pkgload        1.1.0     2020-05-29 [1] CRAN (R 4.0.0)
 plyr           1.8.6     2020-03-03 [1] CRAN (R 4.0.0)
 prettyunits    1.1.1     2020-01-24 [1] CRAN (R 4.0.0)
 processx       3.4.5     2020-11-30 [1] CRAN (R 4.0.3)
 ps             1.5.0     2020-12-05 [1] CRAN (R 4.0.3)
 purrr          0.3.4     2020-04-17 [1] CRAN (R 4.0.0)
 quadprog       1.5-8     2019-11-20 [1] CRAN (R 4.0.0)
 R6             2.5.0     2020-10-28 [1] CRAN (R 4.0.3)
 Rcpp           1.0.6     2021-01-15 [1] CRAN (R 4.0.3)
 remotes        2.2.0     2020-07-21 [1] CRAN (R 4.0.2)
 reshape2       1.4.4     2020-04-09 [1] CRAN (R 4.0.0)
 rlang          0.4.10    2020-12-30 [1] CRAN (R 4.0.3)
 rprojroot      2.0.2     2020-11-15 [1] CRAN (R 4.0.3)
 scales         1.1.1     2020-05-11 [1] CRAN (R 4.0.0)
 sessioninfo    1.1.1     2018-11-05 [1] CRAN (R 4.0.0)
 stringi        1.5.3     2020-09-09 [1] CRAN (R 4.0.3)
 stringr        1.4.0     2019-02-10 [1] CRAN (R 4.0.0)
 testthat       3.0.1     2020-12-17 [1] CRAN (R 4.0.3)
 tibble         3.0.6     2021-01-29 [1] CRAN (R 4.0.3)
 tidyselect     1.1.0     2020-05-11 [1] CRAN (R 4.0.0)
 usethis        2.0.0     2020-12-10 [1] CRAN (R 4.0.3)
 vctrs          0.3.6     2020-12-17 [1] CRAN (R 4.0.3)
 withr          2.4.1     2021-01-26 [1] CRAN (R 4.0.3)
```

**Comment by arr951** [comment] 2021-02-09 07:17
Hi Toby

Thanks for this,
Were you able to run my codes and generate a plot using ggplot2 with labels for each line?

I get the same error message with your prostate example (above) as well. This is not just with my codes. 
I am not sure if I need other packages to make directlabels functions working?? Very strange?

Ahmad

**Comment by arr951** [comment] 2021-02-09 08:40
I ran my codes and your codes on a different computer, and it worked with no error message! Not sure what causes the error message when I use my laptop???

**Comment by tdhock** [comment] 2021-02-09 14:42
closing since this is probably due to a version problem. are you using the most recent version of R? If not please upgrade. Also please try updating all CRAN packages to most recent versions,
```r
update.packages(ask=FALSE)
```

**Closed by tdhock** 2021-02-09 14:42 UTC

**Comment by arr951** [comment] 2021-02-09 20:50
Thanks! for your information, I even un-installed and reinstalled R and Rstudio and got the latest version of packages.
Here is the info system; but the problem is still exist. 

> devtools::session_info()
- Session info --------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Sydney            
 date     2021-02-10                  

- Packages ------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)
 cachem        1.0.1   2021-01-21 [1] CRAN (R 4.0.3)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.3)
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.3)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.3)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.3)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.3)
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.3)
 ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      3.0.1   2020-12-17 [1] CRAN (R 4.0.3)
 tinytex       0.29    2021-01-21 [1] CRAN (R 4.0.3)
 usethis       2.0.0   2020-12-10 [1] CRAN (R 4.0.3)
 withr         2.4.0   2021-01-16 [1] CRAN (R 4.0.3)
 xfun          0.20    2021-01-06 [1] CRAN (R 4.0.3)

[1] C:/Users/ahmad/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library
