### ISSUE TITLE
Grouping within geom is not detected

### ISSUE THREAD

**Issue by nacnudus** [tdhock/directlabels#11] opened 2017-02-26 21:05 UTC
Compare `scatter` with `scatter2`.  Both are rendered the same, but when `colour = class` is defined in `geom_point()` instead of `ggplot()`, it isn't detected, causing an error.

``` r
library(ggplot2)
library(directlabels)
scatter <- qplot(jitter(hwy),jitter(cty),data=mpg,colour=class,
                main="Fuel efficiency depends on car size")
print(direct.label(scatter))

scatter2 <-
  ggplot(aes(jitter(hwy), jitter(cty)), data = mpg) +
  geom_point(aes(colour = class))
print(direct.label(scatter2))
#> Error: Each variable must have a unique name.
#> Problem variables: 'colour'
```

Thanks for the very cool package, though.

**Comment by tdhock** [comment] 2017-03-24 20:51
I can't reproduce this error, so I'm closing for now.
```r
> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_CA:en                    
 collate  en_CA.UTF-8                 
 tz       America/Montreal            
 date     2017-03-24                  

Packages -----------------------------------------------------------------------
 package      * version     date       source                              
 assertthat     0.1         2013-12-06 CRAN (R 3.0.2)                      
 colorspace     1.2-6       2015-03-11 CRAN (R 3.2.3)                      
 devtools       1.12.0.9000 2016-08-12 Github (hadley/devtools@565ac15)    
 digest         0.6.10      2016-08-02 CRAN (R 3.2.3)                      
 directlabels * 2017.01.03  2017-01-04 Github (tdhock/directlabels@dcf3467)
 ggplot2      * 2.2.1       2016-12-30 CRAN (R 3.3.3)                      
 gtable         0.2.0       2016-02-26 CRAN (R 3.2.3)                      
 labeling       0.3         2014-08-23 CRAN (R 3.2.3)                      
 lazyeval       0.2.0       2016-06-12 CRAN (R 3.3.3)                      
 magrittr     * 1.5         2014-11-22 CRAN (R 3.2.0)                      
 memoise        1.0.0       2016-01-29 CRAN (R 3.2.3)                      
 munsell        0.4.3       2016-02-13 CRAN (R 3.2.3)                      
 plyr           1.8.4       2016-06-08 CRAN (R 3.2.3)                      
 quadprog       1.5-5       2013-04-17 CRAN (R 3.0.2)                      
 Rcpp           0.12.7      2016-09-05 cran (@0.12.7)                      
 scales         0.4.1       2016-11-09 CRAN (R 3.3.2)                      
 tibble         1.2         2016-08-26 CRAN (R 3.3.1)                      
 withr          1.0.2       2016-06-20 CRAN (R 3.2.3)                      
> 
```

**Closed by tdhock** 2017-03-24 20:51 UTC
