### ISSUE TITLE
Direct Labels removing fill legend but labeling colour

### ISSUE THREAD

**Issue by eliocamp** [tdhock/directlabels#8] opened 2016-09-20 23:43 UTC
Hi! I'm making a plot with two climate fields, one displayed as a geom_tile with the fill aesthetic mapped to the variable and the other displayed with geom_contour mapped to colour. Direct Labels correctly puts labels near the contours and removing the unnecessary colour legend. The problem is that it's also removing the most necessary fill legend.

Maybe there's a way to override the default behaviour but I couldn't find it. 

Thanks.

**Comment by tdhock** [comment] 2016-09-26 16:47
Not sure if I understand the problem. Can you please provide a reproducible data and code example?

are you using `direct.label` (hides legends) or `geom_dl` (does not)?

**Comment by eliocamp** [comment] 2016-10-24 14:19
I'm using direct.label. Here's a reproductible code:

`library(ggplot2)
library(directlabels)
grid <- expand.grid(lon = seq(0, 360, by = 2), lat = seq(-90, 0, by = 2))
grid$z1 <- with(grid, cos(lat*pi/180))
grid$z2 <- with(grid, 2*sin(lon*pi/180))

g <- ggplot(grid, aes(lat, lon)) + 
  geom_tile(aes(fill = z1)) +
  geom_contour(aes(z = z2, color = ..level..)) +
  scale_color_gradient(low = "black", high = "black")  # this is so that lines are all black

# This shows legends for the fill aesthetic AND the colour aesthetic,
# as it should. 
print(g)

# This removes the colour label, appropriately, but also
# removes the fill label, which should not happen. 
direct.label(g, "bottom.pieces")
`

The problem seems to be the scale_color_gradient definition. Removing it or using one with different colours, solves the problem. 

`
library(ggplot2)
library(directlabels)
grid <- expand.grid(lon = seq(0, 360, by = 2), lat = seq(-90, 0, by = 2))
grid$z1 <- with(grid, cos(lat*pi/180))
grid$z2 <- with(grid, 2*sin(lon*pi/180))

g <- ggplot(grid, aes(lat, lon)) + 
  geom_tile(aes(fill = z1)) +
  geom_contour(aes(z = z2, color = ..level..)) +
  scale_color_gradient(low = "#000000", high = "#010101")

direct.label(g, "bottom.pieces") # This works ok. 
`

**Comment by tdhock** [comment] 2016-10-25 14:17
this is a pretty strange usage, since the all-black color legend in `g.black` is not informative.

```r
library(ggplot2)
library(directlabels)
grid <- expand.grid(lon = seq(0, 360, by = 2), lat = seq(-90, 0, by = 2))
grid$z1 <- with(grid, cos(lat*pi/180))
grid$z2 <- with(grid, 2*sin(lon*pi/180))

g <- ggplot(grid, aes(lat, lon)) + 
  geom_tile(aes(fill = z1)) +
  geom_contour(aes(z = z2, color = ..level..)) 

g.black <- g+
  scale_color_gradient(low = "black", high = "black")  # this is so that lines are all black

print(g.black)  # Correctly show both legends

direct.label(g.black, "bottom.pieces") # Shows no legend

g.bw <- g+
  scale_color_gradient(low = "black", high = "white")

print(g.bw)

direct.label(g.bw, "bottom.pieces") # This works ok. 
```

I suggest you do not use `aes(color)` and instead use `geom_dl` 

```r
ggplot(grid, aes(lat, lon, z=z2)) + 
  geom_tile(aes(fill = z1))+
  geom_contour(color="black")+
  geom_dl(aes(label=..level..), method="bottom.pieces", stat="contour")
```

Does that work for you?

**Comment by eliocamp** [comment] 2016-10-26 14:10
Thanks! I was doing that because I didn't realise that you could use the ..level.. variable outside the geom_contour() so I thought I had no variable to use as label in geom_dl(). My bad. 
I still think is a bug since there should be no reason for direct.label() to remove the fill legend if it labels the color aesthetic.

**Comment by tdhock** [comment] 2016-10-26 15:25
agreed it is still technically a bug, but since it is such a strange use case, and there is a workaround, I don't really want to spend time fixing it.

If you want to try fixing it, fork the code, add a test to https://github.com/tdhock/directlabels/blob/master/tests/ggplot.R and then open a new PR. but for now I'm closing this.

**Closed by tdhock** 2016-10-26 15:25 UTC
